spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: users
              uri: lb://users
              predicates:
                - Path=/api/v1/user/**
            - id: cars
              uri: lb://cars
              predicates:
                - Path=/api/v1/car/**
            - id: bikes
              uri: lb://bikes
              predicates:
                - Path=/api/v1/bike/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost

server:
  port: 8090  